genome:
    models:
       - "VAGOsolutions/Llama-3-SauerkrautLM-8b-Instruct"
       - "D:/Uni/Masterarbeit Code/jakob_finetuning/finetuned_models/meta_llama_full_colab_remerge_2"
    merge_method: dare_ties
    base_model: "D:/Uni/Masterarbeit Code/jakob_finetuning/finetuned_models/meta_llama_full_colab_remerge_2"
    tokenizer_source: "VAGOsolutions/Llama-3-SauerkrautLM-8b-Instruct"
    layer_granularity: 8
tasks:
  - name: absa
    metric: exact_match