genome:
    models:
       - "VAGOsolutions/Llama-3-SauerkrautLM-8b-Instruct"
       - "Alpaca69B/llama3-8b-whatsapp-app-reviews-absa"
    merge_method: dare_ties
    base_model: "Alpaca69B/llama3-8b-whatsapp-app-reviews-absa"
    tokenizer_source: "VAGOsolutions/Llama-3-SauerkrautLM-8b-Instruct"
    layer_granularity: 8
tasks:
  - name: acsa